# Generated by Django 6.2.dev20260926051415 on 2026-09-29 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_url', models.URLField(max_length=2048)),
                ('submitted_by', models.CharField(default='SYSTEM', max_length=150)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Queued in Broker'), ('TRIAGING', 'L1 Fast Triage'), ('HEADLESS_RUNNING', 'L2 Headless Crawl Active'), ('ANALYZING', 'Vector Analysis In Progress'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Scan Failed')], db_index=True, default='PENDING', max_length=20)),
                ('triage_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scan Job',
                'verbose_name_plural': 'Scan Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('asn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('asn_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('country_iso', models.CharField(default='UNKNOWN', max_length=5)),
                ('dns_records', models.JSONField(default=dict)),
                ('ssl_issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('ssl_valid_from', models.DateTimeField(blank=True, null=True)),
                ('ssl_valid_to', models.DateTimeField(blank=True, null=True)),
                ('ssl_jarm_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_redirect_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('redirect_chain', models.JSONField(default=list)),
                ('scan_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_metadata', to='threats.scanjob')),
            ],
            options={
                'verbose_name': 'Page Metadata',
                'verbose_name_plural': 'Page Metadata',
            },
        ),
        migrations.CreateModel(
            name='FeatureExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom_title', models.CharField(blank=True, max_length=512)),
                ('dom_meta_description', models.TextField(blank=True)),
                ('dom_sha256', models.CharField(db_index=True, max_length=64)),
                ('matched_lexicon_keywords', models.JSONField(default=list)),
                ('has_deceptive_login_form', models.BooleanField(default=False)),
                ('has_hidden_iframe', models.BooleanField(default=False)),
                ('has_telegram_exfiltration', models.BooleanField(default=False)),
                ('exfiltration_endpoints', models.JSONField(default=list)),
                ('scan_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='threats.scanjob')),
            ],
            options={
                'verbose_name': 'Feature Extraction',
                'verbose_name_plural': 'Feature Extractions',
            },
        ),
        migrations.CreateModel(
            name='AuditScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_heuristic_score', models.FloatField()),
                ('nlp_prob_score', models.FloatField(default=0.0)),
                ('visual_score', models.FloatField(default=0.0)),
                ('penalties_applied', models.JSONField(default=dict)),
                ('final_threat_score', models.PositiveSmallIntegerField(db_index=True)),
                ('final_verdict', models.CharField(choices=[('BENIGN', 'Safe / Clean'), ('JUDOL', 'Online Gambling (Judi Online)'), ('SCAM', 'Financial Scam / Social Engineering'), ('PHISHING', 'Phishing / Credential Harvesting'), ('DEFACEMENT', 'Government / Academic Defacement'), ('MALWARE', 'Malicious APK / Trojan Distribution')], db_index=True, max_length=50)),
                ('is_escalated_to_regulator', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_log', to='threats.scanjob')),
            ],
            options={
                'verbose_name': 'Audit Score Log',
                'verbose_name_plural': 'Audit Score Logs',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=30)),
                ('storage_path', models.CharField(max_length=1024)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='threats.scanjob')),
            ],
            options={
                'verbose_name': 'Scraped Asset',
                'verbose_name_plural': 'Scraped Assets',
            },
        ),
        migrations.CreateModel(
            name='TargetDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('apex_domain', models.CharField(db_index=True, max_length=255)),
                ('tld', models.CharField(db_index=True, max_length=50)),
                ('is_cc_tld_id', models.BooleanField(db_index=True, default=False)),
                ('is_gov_or_ac_id', models.BooleanField(db_index=True, default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('current_reputation_score', models.IntegerField(default=0)),
                ('is_whitelisted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Target Domain',
                'verbose_name_plural': 'Target Domains',
                'indexes': [models.Index(fields=['apex_domain', 'is_gov_or_ac_id'], name='threats_tar_apex_do_9e912f_idx'), models.Index(fields=['current_reputation_score'], name='threats_tar_current_6d08d1_idx')],
            },
        ),
        migrations.AddField(
            model_name='scanjob',
            name='target_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='threats.targetdomain'),
        ),
        migrations.CreateModel(
            name='FinancialMuleIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(max_length=50)),
                ('account_number', models.CharField(db_index=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('qris_raw_payload', models.TextField(blank=True)),
                ('cekrekening_status', models.CharField(default='UNCHECKED', max_length=50)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mule_identifiers', to='threats.scanjob')),
            ],
            options={
                'verbose_name': 'Financial Mule Identifier',
                'verbose_name_plural': 'Financial Mule Identifiers',
                'indexes': [models.Index(fields=['institution_type', 'account_number'], name='threats_fin_institu_ad4698_idx')],
            },
        ),
    ]
